### ISSUE TITLE
IFC 4x3 from CIVIL 3D does not work

### ISSUE THREAD

**Issue by LukasKStavario** [ThatOpen/engine_fragment#58]
### Describe the bug 📝

If I convert CIVIL 3D IFC to fragments I am unable to load it. I am getting malformed boxes error.

    const serializer = new FRAGS.IfcImporter();
    serializer.wasm.path = "/";
    const exported = await serializer.process({
            readFromCallback: true,
            // bytes: stream.totalBytes, // total bytes from the stream
            // no `bytes` needed here
            readCallback: readCallback,
            raw: true,
        });
    await fragments.core.load(buffer, {
        modelId: id.toString(),
        // @ts-ignore
        camera: world.camera.three,
        raw: true,
    });

### System Info 💻

```shell
npm start
```

### Used Package Manager 📦

npm

### Error Trace/Logs 📃

worker.mjs:6 Error: Fragments: Malformed boxes!
    at yd.newLookup (worker.mjs:7:271987)
    at new yd (worker.mjs:7:270922)
    at new zd (worker.mjs:7:279449)
    at Td.createModel (worker.mjs:7:283390)
    at Td.execute (worker.mjs:7:283207)
    at Wo.thread.actions.<computed> (worker.mjs:7:46687)
    at Si._handleInput (worker.mjs:7:286765)
    at Si.manageConnection (worker.mjs:6:122464)
    at Si.manageInput (worker.mjs:6:122564)
    at MessagePort.<anonymous> (worker.mjs:6:121765)

### Validations ✅

- [x] Read the [docs](https://docs.thatopen.com/intro).
- [x] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [x] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sample2004** [comment]
Some CIVIL IFC's give this bug too!
example ifc to txt renamed!

[456.txt](https://github.com/user-attachments/files/21425171/456.txt)

**Comment by LukasKStavario** [comment]
Hi, would you fix it? Or we need to run our build and fix it? What is your priority to do that?

**Comment by agviegas** [comment]
It was easier than expected. Should be fixed in @thatopen/fragments@3.1.3. Let us know otherwise

**Comment by LukasKStavario** [comment]
Unfortunately, it didn't help. I can convert to fragments, but the model is nowhere to be seen. The model shared by another community member also behaves strangely after translation. When trying to load it into SingleThreadedFragmentsModel, I still get an error about malformed fragments.

https://www.uschovna.cz/zasilka/TH4YWZDPALZSKJ7R-WGB/

File reading finished! Starting conversion to fragments...
loadWorker.js:64
Tue Jul 29 2025 10:09:24 GMT+0200 (středoevropský letní čas)
loadWorker.js:65
Tue Jul 29 2025 10:09:27 GMT+0200 (středoevropský letní čas)
loadWorker.js:86
IFC processing finished.
loadWorker.js:87
Error closing file: Error: EBADF: bad file descriptor, close
    at Module.closeSync (c:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\lib\fs.js:526:11)
    at loadAndProcessIfc (c:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\loadWorker.js:144:16)
    at async processIfcFile (file:///C:/Users/lkluc/repos/BimCon/Valid%C3%A1tor/validator-react/SG%20DSS%20valid%C3%A1tor%20react/bim-viewer-translation-server/loadWorker.js:161:23) {errno: -4083, code: 'EBADF', syscall: 'close', stack: 'Error: EBADF: bad file descriptor, close
    …ewer-translation-server/loadWorker.js:161:23)', message: 'EBADF: bad file descriptor, close'}

loadWorker.js:147
Error during IFC processing with stream: Error: Fragments: Malformed boxes!
    at xc.newLookup (C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\node_modules\@thatopen\fragments\dist\index.cjs:2:215820)
    at new xc (C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\node_modules\@thatopen\fragments\dist\index.cjs:2:214755)
    at new Vc (C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\node_modules\@thatopen\fragments\dist\index.cjs:2:223773)
    at new exports.SingleThreadedFragmentsModel (C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\node_modules\@thatopen\fragments\dist\index.cjs:2:276871)
    at loadAndProcessIfc (c:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\loadWorker.js:88:23)
    at async processIfcFile (file:///C:/Users/lkluc/repos/BimCon/Valid%C3%A1tor/validator-react/SG%20DSS%20valid%C3%A1tor%20react/bim-viewer-translation-server/loadWorker.js:161:23) {stack: 'Error: Fragments: Malformed boxes!
    at xc.…ewer-translation-server/loadWorker.js:161:23)', message: 'Fragments: Malformed boxes!'}

loadWorker.js:149
Temporary file cleaned up: C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\ifc_305_52686106-6c8b-4ee8-aec9-a566666c3709.ifc
loadWorker.js:173
Error processing IFC file for id 305: Error: Fragments: Malformed boxes!
    at xc.newLookup (C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\node_modules\@thatopen\fragments\dist\index.cjs:2:215820)
    at new xc (C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\node_modules\@thatopen\fragments\dist\index.cjs:2:214755)
    at new Vc (C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\node_modules\@thatopen\fragments\dist\index.cjs:2:223773)
    at new exports.SingleThreadedFragmentsModel (C:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\node_modules\@thatopen\fragments\dist\index.cjs:2:276871)
    at loadAndProcessIfc (c:\Users\lkluc\repos\BimCon\Validátor\validator-react\SG DSS validátor react\bim-viewer-translation-server\loadWorker.js:88:23)
    at async processIfcFile (file:///C:/Users/lkluc/repos/BimCon/Valid%C3%A1tor/validator-react/SG%20DSS%20valid%C3%A1tor%20react/bim-viewer-translation-server/loadWorker.js:161:23) {stack: 'Error: Fragments: Malformed boxes!
    at xc.…ewer-translation-server/loadWorker.js:161:23)', message: 'Fragments: Malformed boxes!'}

**Comment by LukasKStavario** [comment]
Thank you, it works for me.
